version: '3.8'

services:

  dai-pw04:
    image: ghcr.io/heig-lherman/dai-pw04:latest
    command: "server"
    labels:
      ## Traefik
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.services.api-https.loadbalancer.server.port=8080
      ## HTTP
      - traefik.http.routers.api-http.entrypoints=http
      - traefik.http.routers.api-http.rule=Host(`api.dai.heig.lutonite.dev`)
      # We add a middleware to redirect HTTP to HTTPS
      - traefik.http.routers.api-http.middlewares=redirect-to-https
      ## HTTPS
      # We add the HTTPS configuration
      - traefik.http.routers.api-https.entrypoints=https
      - traefik.http.routers.api-https.rule=Host(`${API_FQDN}`)
      - traefik.http.routers.api-https.tls=true
      - traefik.http.routers.api-https.tls.certresolver=letsencrypt
    networks:
      - traefik

networks:
  traefik:
    external: true
